spring:
  application:
      name: abcdefg-eureka
  profiles:
      active: dev  #dev
  security:
      user:
        name: abcdefg
        password: abcdefg

server:
  port: 9999


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS