spring:
  cloud:
    client:
      ipAddress: localhost
  profiles: dev
  datasource-log:
      url: jdbc:mysql://47.92.138.95:3306/abcdefg?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
      username: root
      password: root
      filters: log4j,wall,mergeStat

eureka:
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true
    ipAddress: ${spring.cloud.client.ipAddress}
    hostname: ${spring.cloud.client.ipAddress}

  client:
    serviceUrl:
      defaultZone: http://abcdefg:abcdefg@${spring.cloud.client.ipAddress}:9999/eureka/
  server:
      waitTimeInMsWhenSyncEmpty: 0
      enable-self-preservation: false
      eviction-interval-timer-in-ms: 4000

