spring:
  cloud:
    client:
      ipAddress: localhost
  profiles: dev
  datasource:
    url: jdbc:mysql://47.92.138.95:3306/abcdefg?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: root
    filters: log4j,wall,mergeStat

#=========================================#
zuul:
  routes:
    consumer:
      serviceId: abcdefg-consumer
      path: /consumer/**
      custom-sensitive-headers: true   #传递header
    oauth:   #鉴权服务
      serviceId: abcdefg-oauth
      path: /oauth/**
      custom-sensitive-headers: true   #传递header
#=========================================#




eureka:
  instance:
    perferIpAddress: true   #如果true,使用IP(ipAddress)注册，如果不是则使用主机名（hostname），如果没有ipAddress属性，spring自动寻找回环IP的第一个
    ipAddress: ${spring.cloud.client.ipAddress}  #如果定义该属性，默认直接取该属性配置的IP
    instanceId: ${spring.cloud.client.ipAddress}:${server.port}
    hostname: ${spring.cloud.client.ipAddress}   #如果没有的话，eureka地址不可用
  client:
    registerWithEureka: true    #表示本应用是否是向注册中心注册自己（配置高可用的时候需要设置为true,也就是默认值）
    fetchRegistry: true   #是否去检索服务
    serviceUrl:
      defaultZone: http://abcdefg:abcdefg@localhost:9999/eureka/

