server:
  port: 8003 #项目端口

spring:
  application:
    name: producer3
  profiles:
    active: dev  #dev
  security:
    user:
      name: panlicun
      password: panlicun

###################  mybatis-plus配置  ###################
mybatis-plus:
  mapper-locations: classpath*:com/plc/abcdefg/producer3/modular/*/mapper/sqlMapperXml/*Mapper.xml
  typeAliasesPackage: com.plc.abcdefg.kernel.model
  global-config:
    id-type: 0  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true
    logic-delete-value: 0
    logic-not-delete-value: 1
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  configuration:
    map-underscore-to-camel-case: false
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用

logging:
  config: classpath:logback.xml
  level:
    root: info

#actuator相关配置
#info:
#  build:
#    name: @project.artifactId@
#    encoding: @project.build.sourceEncoding@
#    java:
#      source: @java.version@
#      target: @java.version@
#management:
#  endpoints:
#    web:
#      exposure:
#        #加载所有的端点，默认只加载了info、health
#        include: '*'
#  endpoint:
#    health:
#      show-details: always
#    #可以关闭指定的端点
#    shutdown:
#      enabled: false
