spring:
  application:
    name: abcdefg-consumer
  profiles:
    active: dev  #dev

server:
  port: 8888

# 自定义负载均衡策略
#自定义使用随机策略，producer2是服务应用名,如果不写服务名称则对所有服务都使用该策略
producer2:
   ribbon:
     NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule


hystrix:
  shareSecurityContext: true
  threadpool:
    default:
      coreSize: 600 #并发执行的最大线程数，默认10
      maxQueueSize: 1500 #BlockingQueue的最大队列数
      queueSizeRejectionThreshold: 1000 #即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝
      execution:
        timeout:
          enabled: true
        isolation:
          strategy: THREAD
          semaphore:
            maxConcurrentRequests: 1000
          thread:
            timeoutInMilliseconds: 30000
  command:
    default:
      circuitBreaker:
        sleepWindowInMilliseconds: 100000
        forceClosed: true
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

feign:
  hystrix:
    # 在feign中开启hystrix功能，默认情况下feign不开启hystrix功能
    enabled: true
  ## 配置httpclient线程池
  httpclient:
    enabled: true
  okhttp:
    enabled: false
  compression:  #开启压缩功能
    response:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048

logging:
  config: classpath:logback.xml
  level:
    root: info
    com.plc.consumer.modular.user.service.Producer2Remote: DEBUG  #feign的日志，需要配合配置文件中的日志使用
